Add cxx standard to orocos_kdl CMakeLists.txt
ros2/orocos_kinematics_dynamics pull request #12
Opened 2019-09-07 15:13 UTC by ChuiVanfleet

I was having issues compiling orocos_kdl as part of the ros2 dashing build. Adding the cxx standard to the CMakeLists.txt fixed the issue.

Related to [#185](https://github.com/orocos/orocos_kinematics_dynamics/issues/185)

2019-09-10 19:32 UTC, clalancette commented
Can you explain a little bit more about your environment when you ran into the problem?  I'm not against the idea, but since we don't see any problem in our CI or buildfarm, I'd like to know exactly what this is fixing.  There are also some issues with the implementation, but I'll address that once I know the actual problem.

2019-09-10 20:34 UTC, ChuiVanfleet commented
For sure! I saw the issue while attempting to build the repo in a docker container set up with dependencies for ros2, ros1 installed, etc. I had the same issue with an ubuntu xenial and an ubuntu bionic docker image. It produce compile issues saying that std::shared_ptr couldn't be found, among other c++11 specific types.

If it's something wrong in our environment, I can poke around more and see if I can resolve that instead of having you accept this pr.

2019-09-11 12:09 UTC, clalancette commented
> If it's something wrong in our environment, I can poke around more and see if I can resolve that instead of having you accept this pr.

That would be great.  At the very least, a Dockerfile showing the steps that cause the problem would be useful for identifying the problem for the future.  Thanks in advance.

2019-10-24 07:44 UTC, wjwwood commented
@clalancette can you update the status of the pr?

2019-10-24 13:48 UTC, clalancette commented
Looking back at this, there is no real reason why we shouldn't set the CXX_STANDARD in here; we do it in all of our other packages.  I'll do a quick review on this.

2019-10-24 13:50 UTC, clalancette requested changes

2019-10-24 13:50 UTC, clalancette commented on orocos_kdl/CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 11)
So in all of the other packages where we do this (like https://github.com/ros2/rclcpp/blob/8cc2a9ba8304b61f240f040bc31414502aaa412c/rclcpp/CMakeLists.txt#L20), we always use a style like:

```
if(NOT CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 14)
endif()
```

Please switch to that.  Once that is done, we can merge this.  Thanks!

2019-10-24 14:24 UTC, ChuiVanfleet commented
How's that?

2019-10-24 14:31 UTC, clalancette approved these changes
Looks good to me, thanks for iterating!

2019-10-24 16:30 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8546)](http://ci.ros2.org/job/ci_linux/8546/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4417)](http://ci.ros2.org/job/ci_linux-aarch64/4417/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6966)](http://ci.ros2.org/job/ci_osx/6966/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=8457)](http://ci.ros2.org/job/ci_windows/8457/)

2019-10-24 18:35 UTC, mjcarroll approved these changes

2019-10-24 18:37 UTC, merged